nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.0.cjs
npmScopes:
  mobiscroll:
    npmAlwaysAuth: true
    npmAuthToken: mQ73owwed8675CV6mlrZ8Sq+q4lv6ZfmQWNq3Ai3bQIw6OdQl5wA6OYI63umh8tS
    npmRegistryServer: "https://npm.mobiscroll.com"